- hosts: webservers
  roles:
    - role: java
    - role: tomcat
      vars:
        install_dir: /opt/tomcat
        JAVA_HOME: "{{ hostvars[inventory_hostname]['JAVA_HOME'] }}"
    - role: app
      vars:
        install_dir: "{{ hostvars[inventory_hostname]['TOMCAT'] }}/webapps"
    - role: nginx
      vars:
        app_port: 8080

