---
- name: Install nginx
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  become: yes

- name: Add nginx main conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
    mode: 0644
    owner: root
  become: yes

- name: Add tomcat configuration
  template:
    src: nginx.tomcat.j2
    dest: /etc/nginx/conf.d/nginxtomcat.conf
  become: yes

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
