---
- name: Download tomcat and untar
  unarchive:
    src: "{{ src }}"
    dest: "{{ install_dir }}"
    creates: "{{ config }}"
    remote_src: yes
  become: yes

- name: Create group tomcat
  group:
    name: tomcat
    state: present
  become: yes

- name: Create user tomcat
  user:
    name: tomcat
    state: present
    group: tomcat
    shell: /bin/false
    home: "{{ config }}"
  become: yes

- name: Set permission to config
  file:
    path: "{{ config }}"
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes
  become: yes

- name: Set tomcat group permissions to conf
  file:
    path: "{{ config }}/conf"
    state: directory
    group: tomcat
    mode: 0640
    recurse: yes
  become: yes

- file:
    path: "{{ config }}/conf"
    state: directory
    group: tomcat
    mode: 0650
  become: yes

- name: Create tomcat service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  become: yes

- name: Run tomcat
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes

- name: Set fact about tomcat folder
  set_fact:
    TOMCAT: "{{ config }}"
