---
- name: Install java
  yum:
    name: "{{ java_pkg }}"
    state: present
  become: yes

- name: Fetch installed package
  shell: " ls {{ java_path }} | grep {{ java_pkg }}*"
  register: found_files

- name: Get latest java
  set_fact:
    JAVA_FOLDER: "{{ found_files.stdout_lines | sort(attribute='mtime',reverse=true) | first }}"

- name: Erase any reference to JAVA_HOME before updating
  lineinfile:
    path: /etc/profile
    state: absent
    regexp: '^JAVA_HOME='
  become: yes

- name: Add new JAVA_HOME
  lineinfile:
    path: /etc/profile
    state: present
    line: 'JAVA_HOME={{ java_path }}-{{ JAVA_FOLDER }}/jre'
  become: yes

- name: Set fact
  set_fact:
    JAVA_HOME: '{{ java_path}}-{{ JAVA_FOLDER }}/jre'
